baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ehsan Eqlimi'
theme = 'PaperMod'


# Enable multi-language support
defaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "Ehsan Eqlimi"
    languageName = "English"
    weight = 1
  [languages.fa]
    title = "احسان اقلیمی"
    languageName = "فارسی"
    weight = 2
[params]

  [params.homeInfoParams]
    Title = "Neuroimager"
    Content = """
👋 Welcome!

Working on neuroimaging (EEG, fMRI), signal processing, and machine learning.

Interested in fundamental research.
"""

  [[params.socialIcons]]
    name = "github"
    title = "My GitHub"
    url = "https://github.com/EhsanEqlimi"

[[params.socialIcons]]
  name = "google-scholar"
  url = "https://scholar.google.com/citations?user=JEXmK9wAAAAJ&hl=en"

 [[params.socialIcons]]
    name = "mastodon"
    title = "My Mastodon"
    url = "https://mastodon.social/@ehsan_eqlimi"